# Generated by Django 5.0.3 on 2024-03-07 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaint', models.TextField(null=True)),
                ('medication_given_prior_to_check_up', models.TextField(null=True)),
                ('last_vaccination_given', models.CharField(max_length=100, null=True)),
                ('last_vaccination_date', models.DateField(null=True)),
                ('last_vaccination_brand', models.CharField(max_length=100, null=True)),
                ('last_deworming_given', models.CharField(max_length=100, null=True)),
                ('last_deworming_date', models.DateField(null=True)),
                ('last_deworming_brand', models.CharField(max_length=100, null=True)),
                ('is_transferred_from_other_clinic', models.BooleanField(default=False)),
                ('name_of_clinic', models.CharField(blank=True, max_length=100, null=True)),
                ('case', models.TextField(null=True)),
                ('date_hospitalized', models.DateField(null=True)),
                ('diet', models.TextField(null=True)),
                ('weight', models.FloatField(null=True)),
                ('initial_temp', models.FloatField(null=True)),
                ('heart_rate', models.CharField(max_length=100, null=True)),
                ('respiratory_rate', models.CharField(max_length=100, null=True)),
                ('abnormal_findings', models.TextField(null=True)),
                ('is_cbc', models.BooleanField(null=True)),
                ('is_skin_scrape', models.BooleanField(null=True)),
                ('is_xray', models.BooleanField(null=True)),
                ('is_dfs', models.BooleanField(null=True)),
                ('is_urinalysis', models.BooleanField(null=True)),
                ('is_vaginal_smear', models.BooleanField(null=True)),
                ('tentative_diagnosis', models.TextField(null=True)),
                ('prognosis', models.TextField(null=True)),
                ('treatment_given', models.TextField(null=True)),
                ('take_home_meds', models.TextField(null=True)),
                ('recommendations', models.TextField(null=True)),
                ('followup_checkup_date', models.DateField(default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.pet')),
            ],
        ),
    ]
